--VYPRACOVALI : XMAREK69 (PETR MAREK) a XFRIDR07 (JAN FRIDRICH)

DROP TABLE Kocka CASCADE CONSTRAINTS;
DROP TABLE Zivot CASCADE CONSTRAINTS;
DROP TABLE Teritorium CASCADE CONSTRAINTS;
DROP TABLE Vec CASCADE CONSTRAINTS;
DROP TABLE Hostitel CASCADE CONSTRAINTS;
DROP TABLE Rasa CASCADE CONSTRAINTS;
DROP TABLE Divoka CASCADE CONSTRAINTS;
DROP TABLE Zdomacnena CASCADE CONSTRAINTS;
DROP TABLE Zije CASCADE CONSTRAINTS;
DROP TABLE Vlastni CASCADE CONSTRAINTS;
DROP TABLE Dominuje CASCADE CONSTRAINTS;
DROP TABLE Preferuje CASCADE CONSTRAINTS;
DROP TABLE Zapujceno CASCADE CONSTRAINTS;




CREATE TABLE Kocka 
(
  ID_kocky  INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Hlavni_jmeno VARCHAR(100) NOT NULL,
  Vzorek_kuze VARCHAR(100) NOT NULL,
  Barva_srsti VARCHAR(50) NOT NULL,
  Rod VARCHAR(100) NOT NULL,
  Specificke_znameni VARCHAR(200) NOT NULL,
  Nazev_rasy VARCHAR(30) NOT NULL
);

CREATE TABLE Zivot 
(
  Cislo_zivota  INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Zpusob_smrti VARCHAR(100) NOT NULL,
  Cas_narozeni DATE NOT NULL,
  Cas_umrti DATE NOT NULL,
  ID_kocky  INT NOT NULL,
  ID_teritoria_konce INT NOT NULL,
  ID_teritoria_zacatku INT NOT NULL

);
        
CREATE TABLE Teritorium 
(
  ID_teritoria  INT  GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Typ_teritoria VARCHAR(100) NOT NULL,
  Kapacita_teritoria INT NOT NULL
);
        
CREATE TABLE Vec 
(
  ID_Veci  INT  GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Typ_vlastnictvi VARCHAR(100) NOT NULL,
  Kvantita INT NOT NULL,
  Nazev_Veci VARCHAR(100) NOT NULL,
  ID_teritoria INT NOT NULL
);
        
CREATE TABLE Hostitel 
(
  ID_hostitele  INT  GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Jmeno VARCHAR(100) NOT NULL,
  Datum_narozeni DATE NOT NULL,
  Pohlavi VARCHAR(10) NOT NULL,
  ID_teritoria INT NOT NULL
);

CREATE TABLE Rasa 
(
  Nazev_rasy VARCHAR(30) NOT NULL PRIMARY KEY,
  Barvy_oci VARCHAR(30) NOT NULL,
  Puvod VARCHAR(100) NOT NULL,
  Maximalni_delka_tesaku VARCHAR(100) NOT NULL,  
  Dalsi_specificke_rysy VARCHAR(500) NOT NULL
);
------------GENERALIZACE_RASY------------------------------------
CREATE TABLE Divoka 
( 
  Nazev_rasy VARCHAR(30),
  CONSTRAINT FK_Nazev_rasy_divoke FOREIGN KEY (Nazev_rasy) REFERENCES Rasa(Nazev_rasy),
  Mira_nebezpeci VARCHAR(30) NOT NULL

);

CREATE TABLE Zdomacnena 
(
  Nazev_rasy VARCHAR(30),
  CONSTRAINT FK_Nazev_rasy_zdomancnene FOREIGN KEY (Nazev_rasy) REFERENCES Rasa(Nazev_rasy),
  Datum_ochoceni DATE NOT NULL
);


--------------------vztahy n ku n-----------------------------------------
CREATE TABLE Zije
(
  ID_kocky  INT NOT NULL,
  CONSTRAINT FK_Kocka_v_teritoriu FOREIGN KEY (ID_kocky) REFERENCES Kocka(ID_kocky),
  ID_teritoria INT NOT NULL,
  CONSTRAINT FK_Teritorium_kocky FOREIGN KEY (ID_teritoria) REFERENCES Teritorium(ID_teritoria)

);

CREATE TABLE Vlastni
(
  ID_kocky  INT NOT NULL,
  CONSTRAINT FK_Kocka_Vlastnici_Vec FOREIGN KEY (ID_kocky) REFERENCES Kocka(ID_kocky),
  ID_Veci INT NOT NULL,
  CONSTRAINT FK_Vec_kocky FOREIGN KEY (ID_Veci) REFERENCES Vec(ID_Veci),
  cas_privlastneni DATE NOT NULL,
  cas_odhozeni DATE NOT NULL
);

CREATE TABLE Dominuje
(
  ID_kocky INT NOT NULL,
  CONSTRAINT FK_Kocka_dominuje FOREIGN KEY (ID_kocky) REFERENCES Kocka(ID_kocky),
  ID_hostitele INT NOT NULL,
  CONSTRAINT FK_Hostitel_kocky FOREIGN KEY (ID_hostitele) REFERENCES Hostitel(ID_hostitele),
  Hostitel_nazyva_kocku VARCHAR(100) NOT NULL
);

CREATE TABLE Preferuje
(
  Nazev_rasy  VARCHAR(30) NOT NULL,
  CONSTRAINT FK_Preferovana_rasa FOREIGN KEY (Nazev_rasy) REFERENCES Rasa(Nazev_rasy),
  ID_hostitele INT NOT NULL,
  CONSTRAINT FK_Hostitel_preferujici_rasu FOREIGN KEY (ID_hostitele) REFERENCES Hostitel(ID_hostitele)
);

CREATE TABLE Zapujceno
(
  ID_hostitele  INT NOT NULL,
  CONSTRAINT FK_Zapujceno_hostiteli FOREIGN KEY (ID_hostitele) REFERENCES Hostitel(ID_hostitele),
  ID_Veci INT NOT NULL,
  CONSTRAINT FK_Zapujcena_Vec FOREIGN KEY (ID_Veci) REFERENCES Vec(ID_Veci),
  cas_privlastneni DATE NOT NULL,
  cas_vraceni DATE NOT NULL
);



--------------------------------------------------------------
-------------nastaveni cizich klicov------------------------
--------------------------------------------------------------

ALTER TABLE Kocka ADD CONSTRAINT FK_Rasa_kocky FOREIGN KEY (Nazev_rasy) REFERENCES Rasa(Nazev_rasy);
ALTER TABLE Zivot ADD CONSTRAINT FK_Kocici_Zivot FOREIGN KEY (ID_kocky) REFERENCES Kocka(ID_kocky);
ALTER TABLE Zivot ADD CONSTRAINT FK_Skoncil FOREIGN KEY (ID_teritoria_konce) REFERENCES Teritorium(ID_teritoria);
ALTER TABLE Zivot ADD CONSTRAINT FK_Zacal FOREIGN KEY (ID_teritoria_zacatku) REFERENCES Teritorium(ID_teritoria);
ALTER TABLE Hostitel ADD CONSTRAINT FK_Se_narodil_v FOREIGN KEY (ID_teritoria) REFERENCES Teritorium(ID_teritoria);
ALTER TABLE Vec ADD CONSTRAINT FK_patri_do FOREIGN KEY (ID_teritoria) REFERENCES Teritorium(ID_teritoria);


--vlozeni dat

INSERT INTO Rasa (Nazev_rasy, Barvy_oci, Puvod, Maximalni_delka_tesaku,Dalsi_specificke_rysy) VALUES ('Ocicat', 'modra', 'Dansko', '1 cm', 'male tlapky');
INSERT INTO Rasa (Nazev_rasy, Barvy_oci, Puvod, Maximalni_delka_tesaku,Dalsi_specificke_rysy) VALUES ('American Curl', 'zelena', 'Amerika', '1.2 cm', 'dlouhy ocas');

INSERT INTO KOCKA (HLAVNI_JMENO, VZOREK_KUZE, BARVA_SRSTI, ROD, SPECIFICKE_ZNAMENI, NAZEV_RASY) VALUES ('Mourek', 'flekata', 'hneda', 'Fridrichovci', 'velke oci', 'Ocicat');
INSERT INTO Kocka (Hlavni_jmeno, vzorek_kuze, Barva_srsti, Rod, Specificke_znameni, Nazev_rasy) VALUES ('Tygr', 'flekata', 'hneda', 'Fridrichovci', 'kratky ocas', 'Ocicat');
INSERT INTO Kocka (Hlavni_jmeno, vzorek_kuze, Barva_srsti, Rod, Specificke_znameni, Nazev_rasy) VALUES ('Macek', 'strakata', 'seda', 'Petrovci', 'bile tlapky', 'American Curl');
INSERT INTO Kocka (Hlavni_jmeno, vzorek_kuze, Barva_srsti, Rod, Specificke_znameni, Nazev_rasy) VALUES ('Morris', 'strakata', 'seda', 'Petrovci', 'hunata srst', 'American Curl');

INSERT INTO Teritorium (Typ_teritoria, Kapacita_teritoria) VALUES ('Nemocnice', 200);
INSERT INTO Teritorium (Typ_teritoria, Kapacita_teritoria) VALUES ('Opustena zahrada', 200);
INSERT INTO Teritorium (Typ_teritoria, Kapacita_teritoria) VALUES ('Koupaliste', 300);
INSERT INTO Teritorium (Typ_teritoria, Kapacita_teritoria) VALUES ('Park', 500);
INSERT INTO Teritorium (Typ_teritoria, Kapacita_teritoria) VALUES ('Chata', 100);

INSERT INTO Hostitel (Jmeno, Datum_Narozeni, Pohlavi, ID_Teritoria) VALUES ('Frida', TO_DATE('02-05-1990','DD-MM-YYYY'), 'Muz', 1);
INSERT INTO Hostitel (Jmeno, Datum_Narozeni, Pohlavi, ID_Teritoria) VALUES ('Ondra', TO_DATE('09-02-1995','DD-MM-YYYY'), 'Muz', 5);

INSERT INTO Vec (Typ_vlastnictvi, Kvantita, Nazev_Veci, ID_teritoria) VALUES ('luzkovina', 2, 'Polstar', 1);
INSERT INTO Vec (Typ_vlastnictvi, Kvantita, Nazev_Veci, ID_teritoria) VALUES ('zabava', 1, 'Klubicko', 2);


INSERT INTO Zivot (Zpusob_smrti, Cas_narozeni, Cas_umrti, ID_kocky, ID_teritoria_konce, ID_teritoria_zacatku) VALUES ('Prejeti autem', TO_DATE('05-08-2010','DD-MM-YYYY'), TO_DATE('12-09-2011','DD-MM-YYYY'), 1, 1, 1);
INSERT INTO Zivot (Zpusob_smrti, Cas_narozeni, Cas_umrti, ID_kocky, ID_teritoria_konce, ID_teritoria_zacatku) VALUES ('Smrt starim', TO_DATE('15-06-2011','DD-MM-YYYY'), TO_DATE('18-02-2013','DD-MM-YYYY'), 2, 2, 1);

INSERT INTO Divoka (Nazev_rasy, Mira_nebezpeci) VALUES ('Ocicat','Mirne nebezpecna');

INSERT INTO Zdomacnena (Nazev_rasy, Datum_ochoceni) VALUES ('American Curl',TO_DATE('07-10-2005','DD-MM-YYYY'));

INSERT INTO Zije (ID_kocky, ID_teritoria) VALUES (1, 1);
INSERT INTO Zije (ID_kocky, ID_teritoria) VALUES (2, 2);
INSERT INTO Zije (ID_kocky, ID_teritoria) VALUES (3, 4);
INSERT INTO Zije (ID_kocky, ID_teritoria) VALUES (4, 4);

INSERT INTO Vlastni (ID_kocky, ID_Veci, cas_privlastneni, cas_odhozeni) VALUES (3, 1, TO_DATE('07-10-2005','DD-MM-YYYY'), TO_DATE('07-10-2006','DD-MM-YYYY'));
INSERT INTO Vlastni (ID_kocky, ID_Veci, cas_privlastneni, cas_odhozeni) VALUES (4, 2, TO_DATE('07-10-2006','DD-MM-YYYY'), TO_DATE('07-10-2008','DD-MM-YYYY'));

INSERT INTO Dominuje (ID_kocky, ID_hostitele, Hostitel_nazyva_kocku) VALUES (1, 1, 'Kocourek');
INSERT INTO Dominuje (ID_kocky, ID_hostitele, Hostitel_nazyva_kocku) VALUES (2, 2, 'Kocour');

INSERT INTO Preferuje (Nazev_rasy, ID_hostitele) VALUES ('Ocicat', 1);
INSERT INTO Preferuje (Nazev_rasy, ID_hostitele) VALUES ('American Curl', 2);

INSERT INTO Zapujceno (ID_hostitele, ID_Veci, cas_privlastneni, cas_vraceni) VALUES (2, 1, TO_DATE('07-11-2005','DD-MM-YYYY'), TO_DATE('07-12-2005','DD-MM-YYYY'));
